version: 1.0.{build}
os: Visual Studio 2015

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  - git submodule update --init --recursive

before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - '"C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\sn.exe" -Vr *,c5b62af9de6d7244'

build_script:
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

test:
  assemblies: src\Tests\**\*test*.dll

after_test:
  - ps: Vsix-PushArtifacts -publishToGallery "src\SonarLint.Vsix\bin\Release\SonarLint.vsix"

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
